Add Tag as input
leanix/k8s-deploy-action pull request #17
Opened 2021-09-29 15:04 UTC by stl-leanix

2021-09-29 18:02 UTC, dan-leanix requested changes
@stl-leanix Which story is behind that? I see no ticket number. If you have not created a ticket yet please do so and redo the changes on a new feature branch and close this PR.

2021-09-29 18:02 UTC, dan-leanix commented on action.yml
> +    description: 'tag is required for Krane'
```suggestion
    description: 'container image tag'
```

2021-09-29 18:04 UTC, perbernhardt commented on action.yml
> +  tag:
This is not true. A tag is only required, if your deployment templates ask for it. And you could choose for a completely different name there, e.g. "version".
See https://github.com/Shopify/krane#usage for required parameters.

2021-09-30 06:53 UTC, stl-leanix commented on action.yml
> +    description: 'tag is required for Krane'
Ok I will create a Ticket and redo! I only noticed this warning during our deployments and removed therefore the tag parameter and it crashed 😅 
![Screenshot 2021-09-30 at 08 51 28](https://user-images.githubusercontent.com/48126159/135402158-1fd36190-d364-4bb5-80c7-320808632b15.jpg)

2021-09-30 07:03 UTC, closed without merging

2021-09-30 09:54 UTC, perbernhardt commented on action.yml
> +    description: 'tag is required for Krane'
This is more like a "bug" in Github Actions: There is no way to express that you accept arbitrary inputs, although it is totally allowed to define and use them as a user.
Again: The "tag" variable is something you use inside of your templates, so you cannot remove it from the deployment...